### ISSUE TITLE
Redmine 5.0+ compability

### ISSUE THREAD

**Issue by mindyhub** [m-ramizraja/redmine_group_owners#7]
Hi there
Really appreciate your work and this plugin.
Is there any chance you could update it to work with Redmine v5.0 and above?
Currently I'm getting this error:

```
redmine-app  | <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require': cannot load such file -- group_owners/patches/group_patch (LoadError)
redmine-app  |  from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
redmine-app  |  from /usr/local/bundle/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:34:in `require'
redmine-app  |  from /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
redmine-app  |  from /usr/src/redmine/plugins/redmine_group_owners/lib/group_owners_patches.rb:2:in `<top (required)>'
redmine-app  |  from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
redmine-app  |  from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
redmine-app  |  from /usr/local/bundle/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:26:in `require'
redmine-app  |  from /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
redmine-app  |  from /usr/local/bundle/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
redmine-app  |  from /usr/local/bundle/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/helpers.rb:135:in `cget'
redmine-app  |  from /usr/local/bundle/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:175:in `block in actual_eager_load_dir'
redmine-app  |  from /usr/local/bundle/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
redmine-app  |  from /usr/local/bundle/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/helpers.rb:25:in `each'
redmine-app  |  from /usr/local/bundle/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/helpers.rb:25:in `ls'
redmine-app  |  from /usr/local/bundle/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:170:in `actual_eager_load_dir'
redmine-app  |  from /usr/local/bundle/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
redmine-app  |  from /usr/local/bundle/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:16:in `each'
redmine-app  |  from /usr/local/bundle/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
redmine-app  |  from /usr/local/bundle/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
redmine-app  |  from /usr/local/bundle/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
redmine-app  |  from /usr/local/bundle/gems/zeitwerk-2.6.13/lib/zeitwerk/loader.rb:379:in `block in eager_load_all'
redmine-app  |  from /usr/local/bundle/gems/zeitwerk-2.6.13/lib/zeitwerk/loader.rb:377:in `each'
redmine-app  |  from /usr/local/bundle/gems/zeitwerk-2.6.13/lib/zeitwerk/loader.rb:377:in `eager_load_all'
redmine-app  |  from /usr/local/bundle/gems/railties-6.1.7.7/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
redmine-app  |  from /usr/local/bundle/gems/railties-6.1.7.7/lib/rails/initializable.rb:32:in `instance_exec'
redmine-app  |  from /usr/local/bundle/gems/railties-6.1.7.7/lib/rails/initializable.rb:32:in `run'
redmine-app  |  from /usr/local/bundle/gems/railties-6.1.7.7/lib/rails/initializable.rb:61:in `block in run_initializers'
redmine-app  |  from /usr/local/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
redmine-app  |  from /usr/local/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
redmine-app  |  from /usr/local/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
redmine-app  |  from /usr/local/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
redmine-app  |  from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each'
redmine-app  |  from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `call'
redmine-app  |  from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
redmine-app  |  from /usr/local/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
redmine-app  |  from /usr/local/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
redmine-app  |  from /usr/local/bundle/gems/railties-6.1.7.7/lib/rails/initializable.rb:60:in `run_initializers'
redmine-app  |  from /usr/local/bundle/gems/railties-6.1.7.7/lib/rails/application.rb:391:in `initialize!'
redmine-app  |  from /usr/src/redmine/config/environment.rb:16:in `<top (required)>'
redmine-app  |  from config.ru:3:in `require_relative'
redmine-app  |  from config.ru:3:in `block in <main>'
redmine-app  |  from /usr/local/bundle/gems/rack-2.2.9/lib/rack/builder.rb:116:in `eval'
redmine-app  |  from /usr/local/bundle/gems/rack-2.2.9/lib/rack/builder.rb:116:in `new_from_string'
redmine-app  |  from /usr/local/bundle/gems/rack-2.2.9/lib/rack/builder.rb:105:in `load_file'
redmine-app  |  from /usr/local/bundle/gems/rack-2.2.9/lib/rack/builder.rb:66:in `parse_file'
redmine-app  |  from /usr/local/bundle/gems/rack-2.2.9/lib/rack/server.rb:349:in `build_app_and_options_from_config'
redmine-app  |  from /usr/local/bundle/gems/rack-2.2.9/lib/rack/server.rb:249:in `app'
redmine-app  |  from /usr/local/bundle/gems/rack-2.2.9/lib/rack/server.rb:422:in `wrapped_app'
redmine-app  |  from /usr/local/bundle/gems/rack-2.2.9/lib/rack/server.rb:312:in `block in start'
redmine-app  |  from /usr/local/bundle/gems/rack-2.2.9/lib/rack/server.rb:379:in `handle_profiling'
redmine-app  |  from /usr/local/bundle/gems/rack-2.2.9/lib/rack/server.rb:311:in `start'
redmine-app  |  from /usr/local/bundle/gems/railties-6.1.7.7/lib/rails/commands/server/server_command.rb:39:in `start'
redmine-app  |  from /usr/local/bundle/gems/railties-6.1.7.7/lib/rails/commands/server/server_command.rb:144:in `block in perform'
redmine-app  |  from <internal:kernel>:90:in `tap'
redmine-app  |  from /usr/local/bundle/gems/railties-6.1.7.7/lib/rails/commands/server/server_command.rb:135:in `perform'
redmine-app  |  from /usr/local/bundle/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
redmine-app  |  from /usr/local/bundle/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
redmine-app  |  from /usr/local/bundle/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
redmine-app  |  from /usr/local/bundle/gems/railties-6.1.7.7/lib/rails/command/base.rb:69:in `perform'
redmine-app  |  from /usr/local/bundle/gems/railties-6.1.7.7/lib/rails/command.rb:48:in `invoke'
redmine-app  |  from /usr/local/bundle/gems/railties-6.1.7.7/lib/rails/commands.rb:18:in `<top (required)>'
redmine-app  |  from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
redmine-app  |  from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
redmine-app  |  from bin/rails:4:in `<main>'

```

**Comment by mindyhub** [comment]
redmine 6.0 compatible version https://github.com/hello-ger/redmine_group_owners/tree/redmine6.0-compat
